version: '3.8'

services:
    nginx:
        build:
            context: ./nginx
        container_name: nginx
        restart: always
        ports:
            - '8080:80'
        depends_on:
            - node
        networks:
            - default-network

    node:
        build:
            context: ./node
        container_name: node
        restart: always
        depends_on:
            - db
        networks:
            - default-network

    db:
        build:
            context: ./mysql
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: default-network

networks:
    default-network:
        driver: bridge
